### ISSUE TITLE
[Enhancement] Pypi publish latest releases

### ISSUE THREAD

**Issue by int3rn** [telekom-mms/Automated-Ansible-Role-Documentation#58]
### Description

The latest release in pypi is 1.0.1 not 1.0.3 as released here. Can that be pushed over there as well?

### Additional information

https://pypi.org/project/aar-doc/

**Comment by rndmh3ro** [comment]
Thanks for noticing! The workflow was broken, I fixed it. There's a new release now on Pypi.
