### ISSUE TITLE
[Bug] aar-doc command unknown after installation

### ISSUE THREAD

**Issue by moritzrp** [telekom-mms/Automated-Ansible-Role-Documentation#75]
### Description

The documentation refers to the use of `aar-doc` after the installation. But there is no entry point for `aar-doc`. Instead, `aar_doc` has to be used.

### Reproduction steps

1. Create a fresh virtual environment
2. `pip install aar-doc`
3. `aar-doc [OPTIONS] ROLE_PATH COMMAND [ARGS]...`

### Current Behavior

Result: `aar-doc: command not found`

### Expected Behavior

`aar-doc` should be executed.

### Additional information

version: aar-doc-1.2.0

**Comment by rndmh3ro** [comment]
It's `aar_doc`, with an underscore. I see that the docs are wrong here.. I'll fix them.

**Comment by moritzrp** [comment]
To keep it consistent with the package name I added an entry point for `aar-doc`. Could this be a solution instead?

**Comment by rndmh3ro** [comment]
Good question - I don't know if having both is a good idea from a linux-/shell-/convience standpoint.

**Comment by moritzrp** [comment]
That's fair. My two cents from user perspective: Having a command that is the same name as the package I just installed is the most convenient and expected behavior.

**Comment by rndmh3ro** [comment]
Let's do a hyphen then.
