### ISSUE TITLE
[Enhancement] The markdown template should include the content of the description field

### ISSUE THREAD

**Issue by montaropdf** [telekom-mms/Automated-Ansible-Role-Documentation#78]
### Description

The template `markdown.j2` miss the `description` field of the target role. It only include the `short_description` field content.

Below is a example of the code that could be added to add the content of the `description` field:

``` jinja2

  {% for line in argument_specs[entrypoint].description %}
  {{ line }}
  {% endfor %}
```

**Comment by rndmh3ro** [comment]
See #79.

BTW: you guys should use your own templates. :)

**Comment by montaropdf** [comment]
> See #79.
> 
> BTW: you guys should use your own templates. :)

I understand, however, as far as I know, there is not a lengthy description of what to expect from the `markdown` command. So it is easy to find ways for "improvements". ;)
